name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DOCKERPASS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t  rexanator96/team6_itinerarywebapp:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERPASS }}" | docker login -u "rexanator96" --password-stdin

    - name: Push Docker image
      run: docker push rexanator96/team6_itinerarywebapp:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: team6itinerarywebapp.eastus.cloudapp.azure.com
        username: azureuser
        key: ${{ secrets.LinuxServerKey}}
        script: |
          sudo docker pull your_dockerhub_username/travel-planner
          sudo docker stop travel-planner || true
          sudo docker rm travel-planner || true
          sudo docker run -d -p 5000:5000 --volume $(pwd):/temp --name test rexanator96/team6_itinerarywebapp:latest
